const test=require('node:test'),assert=require('node:assert/strict'),C=require('../department-store-presentation-core.js');
function fixture(){const period=['2026-02','2026-03','2026-04','2026-05','2026-06','2026-07'];return {contract:'north12-scores-brief-v1',period,filters:{},records:period.flatMap((monthKey,i)=>[
 {monthKey,region:'北一二A',store:'合成甲店',score:100,defects:0,deduction:0,metrics:[],source:{score:{cell:'G10'}}},
 {monthKey,region:'北一二B',store:'合成乙店',score:[99,100,98,99,97,99][i],defects:1,deduction:1,metrics:[{kind:'defect',status:'number',value:2,unit:'台日',group:'資安類',label:'電腦未關機',cell:'Z11'},{kind:'defect',status:'number',value:1,unit:'原表單位',group:'文件回送',label:'疏失數',cell:'AA11'},{kind:'total',status:'number',value:3,unit:'原表單位',label:'总计'}]},
 {monthKey,region:'北一二C',store:'合成丙店',score:99.5,defects:1,deduction:.5,metrics:[]}
])};}
test('weighted valid-store-month means and all four regions without inventing data',()=>{const m=C.buildModel(fixture());assert.equal(m.summary.valid,18);assert.equal(m.regions.length,4);assert.equal(m.regions[3].single.mean,null);assert.equal(m.single.perfect,1);assert.equal(m.single.rate,1/3);assert.equal(m.sixPerfect.length,1);assert.equal(m.lowScores.length,2);assert.equal(m.single.continuous,2);});
test('missing month interrupts streak and disqualifies six-month perfect',()=>{const f=fixture();f.records=f.records.filter(r=>!(r.store==='合成乙店'&&r.monthKey==='2026-06')&&!(r.store==='合成甲店'&&r.monthKey==='2026-03'));const m=C.buildModel(f);assert.equal(m.lowScores.find(r=>r.store==='合成乙店').streak,1);assert.equal(m.sixPerfect.length,0);assert.equal(m.storeRows.find(r=>r.store==='合成甲店').mean,100);assert.equal(m.storeRows.find(r=>r.store==='合成甲店').cells[1].score,null);});
test('null excludes denominator while numeric zero remains valid',()=>{const f=fixture();const r=f.records.find(r=>r.store==='合成甲店'&&r.monthKey==='2026-07');r.score=null;f.records.find(r=>r.store==='合成丙店'&&r.monthKey==='2026-07').score=0;const m=C.buildModel(f);assert.equal(m.single.valid,2);assert.equal(m.single.missingStores,1);assert.equal(m.single.mean,49.5);assert.equal(m.lowScores[0].score,0);});
test('fully missing target month never coerces missing percentage to zero',()=>{const f=fixture();for(const r of f.records)if(r.monthKey==='2026-07')r.score=null;const m=C.buildModel(f);assert.equal(m.single.rate,null);assert.equal(m.single.mean,null);assert.doesNotMatch(C.renderPrintHtml(m),/滿分率 0%/);assert.equal(m.sixPerfect.length,0);});
test('selecting fewer than six months never grants six-month qualification',()=>{const m=C.buildModel(fixture(),{startMonth:'2026-05'});assert.equal(m.sixMonthEligibilityEvaluated,false);assert.equal(m.sixPerfect.length,0);assert.equal(m.lowScores.find(r=>r.store==='合成乙店').streak,3);});
test('store and region filters restrict data and cannot broaden filtered inputs',()=>{const m=C.buildModel(fixture(),{region:'北一二B',store:'合成乙店'});assert.equal(m.summary.valid,6);assert.equal(m.storeCount,1);assert.equal(m.regions.length,1);const f=fixture();f.filters={region:'北一二B'};assert.throws(()=>C.buildModel(f,{region:''}),/擴張/);});
test('reason statistics count distinct stores per category and retain units',()=>{const f=fixture();f.records.find(r=>r.store==='合成乙店'&&r.monthKey==='2026-07').metrics.push({kind:'defect',status:'number',value:7,unit:'台日',group:'資安類',label:'電腦未關機',cell:'AB11'});const m=C.buildModel(f);assert.equal(m.reasonTop.find(r=>r.category==='電腦未關機').stores,1);assert.match(C.reasonText(m.lowScores.find(r=>r.store==='合成乙店')),/2 台日/);assert.equal(m.lowScores.find(r=>r.store==='合成乙店').reasons.length,3);});
test('score below 100 identifies loss when legacy defect total excludes recycle',()=>{const f=fixture();const r=f.records.find(r=>r.store==='合成甲店'&&r.monthKey==='2026-07');r.score=99;r.defects=0;r.deduction=1;const m=C.buildModel(f);assert.equal(m.single.low,3);});
test('duplicate records, coercible strings and invalid dates fail closed',()=>{const f=fixture();f.records.push({...f.records[0]});assert.throws(()=>C.buildModel(f),/重複/);const f2=fixture();f2.records[0].score='100';assert.throws(()=>C.buildModel(f2),/數值/);assert.throws(()=>C.buildModel(fixture(),{startMonth:'2026-00'}),/日期/);});
test('automatic continuation preserves all four overflow categories without dropping or repeating data',()=>{
 const m=C.buildModel(require('./fixtures/department-store-presentation-overflow.cjs')()),p=C.planPages(m),tr=p.filter(p=>p.kind==='trend'),mo=p.filter(p=>p.kind==='monthly');
 assert.equal(p.length,6);assert.equal(tr.length,3);assert.equal(mo.length,3);
 assert.deepEqual(tr.flatMap(p=>p.model.regions.flatMap(r=>r.rows)).map(r=>r.store).sort(),m.storeRows.map(r=>r.store).sort());
 assert.deepEqual(tr.flatMap(p=>p.model.sixPerfect).map(r=>r.store),m.sixPerfect.map(r=>r.store));
 assert.deepEqual(mo.flatMap(p=>p.model.lowScores),m.lowScores);assert.deepEqual(mo.flatMap(p=>p.model.reasonTop),m.reasonTop);
 assert.equal((C.renderPrintHtml(m).match(/<main class="page">/g)||[]).length,6);assert.match(C.renderPrintHtml(m),/6 \/ 6/);
});
test('each exact previous boundary continues on a new page',()=>{for(const mutate of [m=>m.regions[0].rows=Array.from({length:11},()=>m.storeRows[0]),m=>m.lowScores=Array.from({length:12},()=>m.lowScores[0]),m=>m.reasonTop=Array.from({length:8},(_,i)=>({category:'合成'+i,stores:1})),m=>m.sixPerfect=Array.from({length:7},()=>m.sixPerfect[0])]){const m=C.buildModel(fixture());mutate(m);assert.equal(C.planPages(m).length,3);}});
test('long reason rows retain font size and reserve extra height before continuation',()=>{const m=C.buildModel(fixture());m.lowScores=Array.from({length:11},(_,i)=>({...m.lowScores[0],order:i+1,reasons:Array.from({length:5},()=>({category:'合成很長的原因分類文字',value:1,unit:'台日'}))}));const pages=C.planPages(m).filter(p=>p.kind==='monthly');assert.ok(pages.length>1);assert.ok(pages[0].model.lowRowHeights[0]>42);assert.equal(pages.flatMap(p=>p.model.lowScores).length,11);});
test('print output escapes untrusted names and is genuinely HTML, not mislabeled PDF',()=>{const f=fixture();for(const r of f.records)if(r.store==='合成甲店')r.store='<script>alert(1)</script>';const html=C.renderPrintHtml(C.buildModel(f));assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>alert/);assert.match(html,/window.print\(\)/);assert.equal((html.match(/<main class="page">/g)||[]).length,2);});
