'use strict';
const {test,expect}=require('@playwright/test'),fs=require('node:fs/promises'),http=require('node:http'),path=require('node:path');
const {createRuntime,parsed,csv,OPERATOR}=require('./helpers/tradein-synthetic-runtime.cjs');
let BASE,server;
test.beforeAll(async()=>{const root=path.resolve(__dirname,'..');server=http.createServer(async(req,res)=>{try{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(path.relative(root,f).startsWith('..'))throw Error();const type={'.html':'text/html','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css'}[path.extname(f)];if(!type)throw Error();res.writeHead(200,{'Content-Type':type+';charset=utf-8'});res.end(await fs.readFile(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));BASE='http://127.0.0.1:'+server.address().port+'/';});
test.afterAll(async()=>{await new Promise(r=>server.close(r));});
async function start(page,{width=390,empty=false,tamper=false}={}){const r=createRuntime(),source=parsed();r.configure(source);if(!empty){const p=r.a.tradeinPerformancePreview({source,employeeId:OPERATOR,adminSecret:r.secret}),value=r.a.tradeinPerformancePublish({source,...p,employeeId:OPERATOR,adminSecret:r.secret});r.a.tradeinPerformancePublicPublish({employeeId:OPERATOR,adminSecret:r.secret,month:source.month,sourceHash:source.source_sha256,expectedActiveHash:value.snapshotHash});}
 const calls=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});await page.clock.install({time:new Date('2026-10-09T14:00:00Z')});
 await page.addInitScript(()=>{localStorage.setItem('north12b_private_dashboard_employee_id','SYNTH01');localStorage.setItem('north12b_private_dashboard_device_id','SYNTHETIC_REVOKED_DEVICE');});
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin===new URL(BASE).origin)return route.continue();if(u.hostname!=='script.google.com')return route.abort();const payload=route.request().postDataJSON();calls.push(payload);const body=r.dispatch(payload);if(tamper&&body.snapshot){body.snapshot.people[0].employee_key='SYNTHETIC_PRIVATE';}return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});});await page.goto(BASE+'tradein-progress.html');return {r,source,calls,errors};}
for(const width of [1280,390,320])test(width+'px unknown month never fabricates counts or uses saved private identity',async({page})=>{const {r,calls,errors}=await start(page,{width,empty:true});await expect(page.locator('#readMessage')).toContainText('保留未知');await expect(page.locator('#publicWorkspace')).toBeHidden();await expect(page.locator('#stats')).toBeEmpty();await expect(page.locator('#staffRows')).toBeEmpty();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(calls).toEqual([{action:'tradein_performance_public_read',month:'2026-10'}]);expect(r.writes.length).toBe(0);expect(errors).toEqual([]);});
